Repository robinostlund/volkswagencarnet, pull requests merged in 2022-02, with the labels that each got.

#147 adding codeql-analysis
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#149 Move source files into subdirectory, update setup configuration
  .gitignore
  README.md
  pyproject.toml
  pytest.ini
  setup.cfg
  setup.py
  tests/__init__.py
  tests/dummy_test.py
  tests/integration_test.py
  volkswagencarnet/__init__.py
  volkswagencarnet/vw_connection.py
  volkswagencarnet/vw_const.py
  volkswagencarnet/vw_dashboard.py
  volkswagencarnet/vw_utilities.py
  volkswagencarnet/vw_vehicle.py
Labels: enhancement

#150 WORK IN PROGRESS - New folder structure
  .github/workflows/release.yaml
  .github/workflows/testrelease.yaml
  .github/workflows/validate.yml
  .gitignore
  README.md
  pyproject.toml
  pytest.ini
  setup.cfg
  setup.py
  tests/__init__.py
  tests/dummy_test.py
  tests/integration_test.py
  volkswagencarnet/__init__.py
  volkswagencarnet/vw_connection.py
  volkswagencarnet/vw_const.py
  volkswagencarnet/vw_dashboard.py
  volkswagencarnet/vw_utilities.py
  volkswagencarnet/vw_vehicle.py
Labels: enhancement

#152 removing version from setup.cfg
  .github/workflows/release.yaml
  .github/workflows/testrelease.yaml
  .github/workflows/validate.yml
Labels: bug

#154 throubleshooting workflows
  .github/workflows/release.yaml
  .github/workflows/testrelease.yaml
  .github/workflows/validate.yml
  pyproject.toml
  setup.cfg
Labels: bug

#155 new folder structure
  .github/workflows/release.yaml
  .github/workflows/testrelease.yaml
  .github/workflows/validate.yml
  pyproject.toml
  setup.cfg
Labels: enhancement

#156 updating readme
  README.md
Labels: enhancement

#157 updating readme
  README.md
Labels: enhancement

#158 changing license
  LICENSE.txt
  setup.cfg
Labels: enhancement

#159 removing tests from package
  .github/workflows/release.yaml
  .github/workflows/testrelease.yaml
  .github/workflows/validate.yml
  .gitignore
  pyproject.toml
  setup.cfg
  volkswagencarnet/vw_connection.py
  volkswagencarnet/vw_const.py
Labels: bug

#160 black lint changes
  tests/dummy_test.py
  tests/integration_test.py
  volkswagencarnet/vw_connection.py
  volkswagencarnet/vw_const.py
  volkswagencarnet/vw_dashboard.py
  volkswagencarnet/vw_utilities.py
  volkswagencarnet/vw_vehicle.py
Labels: enhancement

#162 Better login error handling
  volkswagencarnet/vw_connection.py
Labels: bug

#165 adding codecov test
  .github/workflows/codecov.yaml
  .github/workflows/codeql-analysis.yaml
  .github/workflows/validate.yaml
Labels: enhancement

#166 Files
  .github/workflows/codeql-analysis.yml
  .github/workflows/validate.yml
Labels: enhancement

#164 Tests
  .github/workflows/codecov.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/validate.yml
  .gitignore
  pytest.ini
  requirements-test.txt
  setup.cfg
  tests/conftest.py
  tests/fixtures/__init__.py
  tests/fixtures/connection.py
  tests/fixtures/resources/dummy_cookies.pickle
  tests/vw_connection_test.py
  tests/vw_utilities_test.py
  volkswagencarnet/vw_connection.py
  volkswagencarnet/vw_utilities.py
Labels: enhancement, minor issue

#167 adding snyk
  .github/workflows/snyk.yaml
Labels: enhancement

#168 adding newline to snyk workflow
  .github/workflows/snyk.yaml
Labels: enhancement

#170 Add requirements to pip package
  setup.cfg
Labels: enhancement

#172 Add pre-commit dependency and configuration
  .github/CODEOWNERS
  .github/workflows/release.yaml
  .github/workflows/snyk.yaml
  .github/workflows/testrelease.yaml
  .github/workflows/validate.yml
  .pre-commit-config.yaml
  README.md
  requirements-test.txt
  setup.cfg
Labels: enhancement

#175 Add renovate config
  .github/renovate.json
  setup.cfg
Labels: enhancement, dependencies

#173 Testing tests
  pyproject.toml
  pytest.ini
  requirements-test.txt
  setup.cfg
  tests/vw_connection_test.py
  volkswagencarnet/vw_connection.py
Labels: tests

#176 Fix code scanning alerts (1/x)
  .pre-commit-config.yaml
  pyproject.toml
  requirements-test.txt
  requirements.txt
  tests/conftest.py
  tests/dummy_test.py
  tests/fixtures/connection.py
  tests/integration_test.py
  tests/vw_connection_test.py
  tests/vw_exceptions_test.py
  tests/vw_utilities_test.py
  tests/vw_vehicle_test.py
  volkswagencarnet/vw_connection.py
  volkswagencarnet/vw_dashboard.py
  volkswagencarnet/vw_exceptions.py
  volkswagencarnet/vw_utilities.py
  volkswagencarnet/vw_vehicle.py
Labels: enhancement, tests

#178 Fix code scanning alerts 2
  .pre-commit-config.yaml
  tests/__init__.py
  tests/fixtures/__init__.py
  tests/fixtures/connection.py
  tests/fixtures/resources/responses/status.json
  tests/vw_utilities_test.py
  tests/vw_vehicle_test.py
  volkswagencarnet/__init__.py
  volkswagencarnet/vw_connection.py
  volkswagencarnet/vw_utilities.py
  volkswagencarnet/vw_vehicle.py
Labels: enhancement, tests

#179 Add timer programming feature
  tests/fixtures/connection.py
  tests/fixtures/constants.py
  tests/fixtures/resources/responses/timer.json
  tests/integration_test.py
  tests/vw_connection_test.py
  tests/vw_timer_test.py
  tests/vw_utilities_test.py
  tests/vw_vehicle_test.py
  volkswagencarnet/vw_connection.py
  volkswagencarnet/vw_dashboard.py
  volkswagencarnet/vw_timer.py
  volkswagencarnet/vw_utilities.py
  volkswagencarnet/vw_vehicle.py
Labels: enhancement, tests
