Repository robinostlund/volkswagencarnet, pull requests merged in 2024-02, with the labels that each got.

#247 v4.4.66-beta3
  volkswagencarnet/vw_connection.py
  volkswagencarnet/vw_const.py
  volkswagencarnet/vw_dashboard.py
  volkswagencarnet/vw_vehicle.py
Labels: enhancement

#249 v4.4.66
  volkswagencarnet/vw_connection.py
  volkswagencarnet/vw_const.py
  volkswagencarnet/vw_dashboard.py
  volkswagencarnet/vw_vehicle.py
Labels: enhancement

#240 Add e-Golf response JSON examples
  tests/fixtures/resources/responses/egolf/README.md
  tests/fixtures/resources/responses/egolf/capabilities.json
  tests/fixtures/resources/responses/egolf/last_trip.json
  tests/fixtures/resources/responses/egolf/parkingposition.json
  tests/fixtures/resources/responses/egolf/selectivestatus_by_app.json
Labels: data

#250 v4.4.67
  volkswagencarnet/vw_vehicle.py
Labels: bug

#251 v4.4.68
  tests/fixtures/connection.py
  tests/fixtures/constants.py
  tests/integration_test.py
  tests/vw_timer_test.py
  tests/vw_vehicle_test.py
  volkswagencarnet/vw_connection.py
  volkswagencarnet/vw_dashboard.py
  volkswagencarnet/vw_timer.py
  volkswagencarnet/vw_vehicle.py
Labels: enhancement
